version: '3.1'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8009:80
    depends_on:
      - app
  app:
    image: mparvin/flashcards:latest
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tehran
    env_file:
      - .env

  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - 8085:8080
