version: '3.1'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    ports:
      - 8009:80
    depends_on:
      - app
  app:
    image: mparvin/flashcards:latest
    build: .
    restart: always
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      TZ: Asia/Tehran
    env_file:
      - .env

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8085:8080

volumes:
  pg_data: {}
